language: node_js
node_js:
    - "stable"
before_script:
    - node node_modules/.bin/pm2 start -f test/app/server.js --name=obsidian-proxy-server &
script: grunt jshint browserify:test mocha_phantomjs
